# Generated by Django 5.1.5 on 2025-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_rename_image_newave_image1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                ("static", models.CharField(max_length=155, verbose_name="Статистика")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Хорошо",
            },
        ),
    ]
