# Generated by Django 5.1.5 on 2025-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_good"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="static2",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Статистика"
            ),
            preserve_default=False,
        ),
    ]
