# Generated by Django 5.1.5 on 2025-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_good_static2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="team/", verbose_name="Фото")),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "direction",
                    models.CharField(max_length=100, verbose_name="Напрваление"),
                ),
                ("fb", models.URLField(verbose_name="Ссылка на фейсбук")),
                ("tw", models.URLField(verbose_name="Ссылка на Твитер")),
                ("gl", models.URLField(verbose_name="Ссылка на Гугл")),
            ],
            options={
                "verbose_name_plural": "Наша команда",
            },
        ),
    ]
