# Generated by Django 4.2.7 on 2025-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("descriptio", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("Consultation", "Consultation"),
                            ("Design", "Design"),
                            ("User Experience", "User Experience"),
                            ("Development", "Development"),
                        ],
                        max_length=155,
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Технологий",
            },
        ),
    ]
